### ISSUE TITLE
The link to the guide push-your-first-net-application-to-cloud-foundry-on-azure has been changed.

### ISSUE THREAD

**Issue by AbelHu** [ritazh/s3proxydocker#5]
The link to the guide has been changed to https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/advanced/push-your-first-net-application-to-cloud-foundry-on-azure/README.md.

**Comment by ritazh** [comment]
Thanks @AbelHu 
Closed via ea2c597
